version: '3.7'

services:
    # サービス名は自由に設定
    django:
        # appディレクトリの中から`Dockerfile`を探す
        build: ./app
        # サービス起動後に入力されるコマンドを設定
        command: python manage.py runserver 0.0.0.0:8000
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./app/:/usr/src/app/
        # 開放するポートを指定。`host:container`でポートを記載
        ports:
            - 8000:8000
        # 環境変数を指定
        environment:
            # 1ならデバックモード
            - DEBUG=1
            - SECRET_KEY="#@-atrgft+#-6k&k=_3-=0!*mfw75-ly&1o(42+bv$ku+3w1qv"
            - DATABASE_ENGINE=django.db.backends.mysql
            - DATABASE_DB=django_db
            - DATABASE_USER=django_db_user
            - DATABASE_PASSWORD=password1234
            - DATABASE_HOST=mariadb
            - DATABASE_PORT=3306
        # 接続するサービスを指定
        depends_on:
            - mariadb

    mariadb:
        # 公式からイメージをpull
        image: mariadb:10.5
        # データベースの永続化
        # ホストのディレクトリにマウントしない様に、先頭に`./`をつけない
        volumes:
            - mariadb_data:/var/lib/mysql
        # su権限を持つ、指定されたユーザーと同じ名前のデータベースを作成
        # valueはdjangoサービスで指定したものと同じ様に記載する
        environment:
            - MYSQL_ROOT_PASSWORD=password1234
            - MYSQL_DATABASE=django_db
            - MYSQL_USER=django_db_user
            - MYSQL_PASSWORD=password1234
        expose:
            - 3306
# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    mariadb_data: